name: amptr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/icons/
    - .env

  fonts:
    - family: Red Hat
      fonts:
        - asset: assets/fonts/Red-Hat-Variable.ttf
    - family: Red Hat Bold
      fonts:
        - asset: assets/fonts/Red-Hat-Bold.ttf
          
